#!/bin/bash

if [ "$1" = "help" ] || [ "$1" = "--help" ] || [ -z $1 ]; then
  echo Usage:
  echo package-installer [package name or option]
  echo --help - show this message
  echo --list - show existing scripts
elif [ "$1" = "list" ] || [ "$1" = "--list" ]; then
  python3 <<'EOF'
import re
from sys import argv
from subprocess import check_output, PIPE, Popen
from urllib.request import urlopen


def list_avaliable(link: str) -> list:
    with urlopen(link) as response:
        html = response.read()
    return [
        s.replace('"name":', "").replace('"', "").replace(".sh", "")
        for s in re.findall('"name":"[a-z]+.sh"', str(html))
    ]


link = "https://github.com/XelorR/package-installer/tree/main/apps"
results = list_avaliable(link)
print("Following installation scripts avaliable:")
for i, script in enumerate(results):
    print(f"  {i+1}. {script}")
print("\nRun command with script names to run scripts.\nExamples:")
print("  package-installer neovim")
print("  package-installer sfmono")
print("  package-installer lazygit")
EOF
else
  bash -c "$(curl -sL https://raw.githubusercontent.com/XelorR/package-installer/main/apps/$1.sh)"
fi
